# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl.xci
# IP: The module: 'wr_data_fifo_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data_fifo_ctrl'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data_fifo_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data_fifo_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl.xci
# IP: The module: 'wr_data_fifo_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data_fifo_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data_fifo_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data_fifo_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
