# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/ddr3_ctrl/ddr3_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_ctrl || ORIG_REF_NAME==ddr3_ctrl} -quiet] -quiet

# IP: ip/wr_cmd_fifo_ctrl/wr_cmd_fifo_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wr_cmd_fifo_ctrl || ORIG_REF_NAME==wr_cmd_fifo_ctrl} -quiet] -quiet

# IP: ip/asfifo_wr128x512_rd16x4096/asfifo_wr128x512_rd16x4096.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asfifo_wr128x512_rd16x4096 || ORIG_REF_NAME==asfifo_wr128x512_rd16x4096} -quiet] -quiet

# IP: ip/afifo_wr16x64/afifo_wr16x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_wr16x64 || ORIG_REF_NAME==afifo_wr16x64} -quiet] -quiet

# IP: ip/clk_125_gen/clk_125_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] -quiet

# XDC: ip/ddr3_ctrl/ddr3_ctrl/user_design/constraints/ddr3_ctrl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_ctrl || ORIG_REF_NAME==ddr3_ctrl} -quiet] -quiet

# XDC: ip/ddr3_ctrl/ddr3_ctrl/user_design/constraints/ddr3_ctrl_ooc.xdc

# XDC: ip/clk_125_gen/clk_125_gen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen_ooc.xdc
