# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128.xci
# IP: The module: 'fifo_wr16x1024_rd128x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr16x1024_rd128x128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr16x1024_rd128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128.xci
# IP: The module: 'fifo_wr16x1024_rd128x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr16x1024_rd128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr16x1024_rd128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
