# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen.xci
# IP: The module: 'ddr3_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clk_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen.xci
# IP: The module: 'ddr3_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/fpga_image/vivadoproject_2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/ddr3_clk_gen/ddr3_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
