# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192.xci
# IP: The module: 'afifo_wr8x8192' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_wr8x8192'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_wr8x8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_wr8x8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192.xci
# IP: The module: 'afifo_wr8x8192' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_wr8x8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_wr8x8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/fpga_image/2019.2/GiGe_HDMI/GiGe_HDMI.srcs/sources_1/ip/afifo_wr8x8192/afifo_wr8x8192_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_wr8x8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
