set_property PACKAGE_PIN V17 [get_ports {rx_dat[0]}]
set_property PACKAGE_PIN V18 [get_ports {rx_dat[1]}]
set_property PACKAGE_PIN P19 [get_ports {rx_dat[2]}]
set_property PACKAGE_PIN R19 [get_ports {rx_dat[3]}]
set_property PACKAGE_PIN AB18 [get_ports rx_ctrl]
set_property PACKAGE_PIN T21 [get_ports rx_clk]
set_property PACKAGE_PIN V22 [get_ports phy_rst_n]
set_property PACKAGE_PIN Y18 [get_ports sclkin]
set_property PACKAGE_PIN B21 [get_ports srst_n]
set_property IOSTANDARD LVCMOS33 [get_ports srst_n]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rx_ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports sclkin]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_dat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_dat[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_dat[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_dat[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rx_clk]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]  

set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d0_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d0_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d1_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d1_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d2_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d2_n]
set_property PACKAGE_PIN K4 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN L3 [get_ports hdmi_d0_p]
set_property PACKAGE_PIN L5 [get_ports hdmi_d1_p]
set_property PACKAGE_PIN M3 [get_ports hdmi_d2_p]